version: "2"
linters:
  disable:
    - errcheck
  exclusions:
    rules:
      - text: struct literal uses unkeyed fields
        linters: ["wsl"]
      - text: Error return value of `.*flag.*Parse.*` is not checked
        linters: ["wsl"]
  settings:
    staticcheck:
      checks:
        - all
        - "-QF1008"
        - "-ST1000"
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
