#!/bin/sh

set -e

PUID=${PUID:-0}
PGID=${PGID:-0}
USERNAME=wrtag

[ "$PUID" -eq 0 ] && exec "$@"

adduser -D -u "$PUID" -g "$PGID" "$USERNAME" 2>/dev/null

[ -d "/data" ] && chown -R "$PUID:$PGID" /data
[ -d "/config" ] && chown -R "$PUID:$PGID" /config

exec su-exec "$PUID:$PGID" "$@"
