#!/bin/sh

set -e

PUID=${PUID:-0}
PGID=${PGID:-0}
USERNAME=wrtag

[ "$PUID" -eq 0 ] && exec "$@"

adduser -D -u "$PUID" -g "$PGID" "$USERNAME" 2>/dev/null || true

[ -n "$WRTAG_WEB_DB_PATH" ] && mkdir -p "$(dirname "$WRTAG_WEB_DB_PATH")" && chown "$PUID:$PGID" "$(dirname "$WRTAG_WEB_DB_PATH")"
[ -n "$WRTAG_CONFIG_PATH" ] && chown "$PUID:$PGID" "$(dirname "$WRTAG_CONFIG_PATH")"

exec su-exec "$PUID:$PGID" "$@"
